name: Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: |
          curl -X POST "https://api.netlify.com/build_hooks/6a4575356d0a66fb65ad9fbf"
